### ISSUE TITLE
Issue with hotkeys implementation on Raspberry Pi

### ISSUE THREAD

**Issue by andyinabox** [YCAMInterlab/ofxTimeline#115]
I'm using ofxTimeline for a project which is targeted for Raspberry Pi, and getting the following error when building on RPi:

` ../../../addons/ofxTimeline/src/ofxHotKeys_impl_linux.cpp:24: undefined reference to 'glXGetCurrentDisplay'`

I've only just begun to troubleshoot but I thought I'd mention it here in case anyone has encountered the issue before. Will post or PR as I learn more.

**Comment by obviousjim** [comment]
I have never used timeline on the pi -- perhaps remove this file from the
build?

On Sun, Feb 15, 2015 at 2:14 PM, Andy Dayton <notifications@github.com>
wrote:

> I'm using ofxTimeline for a project which is targeted for Raspberry Pi,
> and getting the following error when building on RPi:
>
> ../../../addons/ofxTimeline/src/ofxHotKeys_impl_linux.cpp:24: undefined
> reference to 'glXGetCurrentDisplay'
>
> I've only just begun to troubleshoot but I thought I'd mention it here in
> case anyone has encountered the issue before. Will post or PR as I learn
> more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YCAMInterlab/ofxTimeline/issues/115>.
>



-- 
- James

**Comment by andyinabox** [comment]
Yup I'm trying that out — will post with results once I know (need to work on my RPi cross-compiling setup, it's taking forever currently!).

**Comment by andyinabox** [comment]
I was able to get this to build on the Pi. My stopgap solution was to fork ofxTimeline and create a version where the modifier keys are disabled:

https://github.com/andyinabox/ofxTimeline/tree/no-hotkeys

Might have been easier to just modify the build, but this worked so I'll roll with it :)

**Comment by moebiussurfing** [comment]
hey @andyinabox , did you made ir work on the last 0.9.x on raspberry pi or osx?

**Comment by andyinabox** [comment]
@moebiussurfing no, this was using oF 0.8.4. 

I haven't yet been able to get ofxTimeline working for 0.9.x, although I did see an oF forum post on the subject: https://forum.openframeworks.cc/t/cant-use-ofxtimeline-with-0-9-0/22076/3
