### ISSUE TITLE
Can't draw anywhere other than (0, 0)

### ISSUE THREAD

**Issue by microcosm** [YCAMInterlab/ofxTimeline#120]
If I want to draw an object on a canvas at the top of the screen and then translate down and draw the timeline below, the mouse pressed actions aren't picked up.

The only place you can draw the timeline is at (0, 0) if you want the mouse to work.

**Comment by obviousjim** [comment]
Try using the serPostion of the timeline instead of translating

On Friday, June 19, 2015, Andrew McWilliams <notifications@github.com>
wrote:

> If I want to draw an object on a canvas at the top of the screen and then
> translate down and draw the timeline below, the mouse pressed actions
> aren't picked up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YCAMInterlab/ofxTimeline/issues/120>.
>


-- 
- James

**Comment by microcosm** [comment]
ofxTimeline has no property or method called 'setPosition'

https://github.com/YCAMInterlab/ofxTimeline/blob/master/src/ofxTimeline.cpp
https://github.com/YCAMInterlab/ofxTimeline/blob/master/src/ofxTimeline.h

**Comment by obviousjim** [comment]
Sorry set offset

void ofxTimeline::setOffset(ofVec2f newOffset){


On Sunday, June 21, 2015, Andrew McWilliams <notifications@github.com>
wrote:

> ofxTimeline has no property or method called 'setPosition'
>
> https://github.com/YCAMInterlab/ofxTimeline/blob/master/src/ofxTimeline.cpp
> https://github.com/YCAMInterlab/ofxTimeline/blob/master/src/ofxTimeline.h
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YCAMInterlab/ofxTimeline/issues/120#issuecomment-113971900>
> .
>


-- 
- James

**Comment by microcosm** [comment]
Got it, this works thanks
